# Streamlit Secrets 配置
DASHSCOPE_API_KEY = "sk-ws-H.EIPEPRY.4X7K.MEQCIA4wbHM2Ts2z_f9TZjbiof2uvR93i9V2Dj3_a4X-ATVVAiAN3_RMhQWIrzV5k0_INH4fGX8Xdxrimf-0wjdHIDnlTg"
DASHSCOPE_CHAT_KEY = "sk-ws-H.EIPEPRY.4X7K.MEQCIA4wbHM2Ts2z_f9TZjbiof2uvR93i9V2Dj3_a4X-ATVVAiAN3_RMhQWIrzV5k0_INH4fGX8Xdxrimf-0wjdHIDnlTg"
